#!/usr/bin/env python

import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('n', type=float)
    parser.add_argument('total', nargs='?', type=float, default=100)
    parser.add_argument('--width', '-w', type=int, default=100)
    args = parser.parse_args()

    ratio = args.n / args.total
    full_char_num = round(ratio * args.width)
    empty_char_num = args.width - full_char_num

    print(
        full_char_num * '\N{FULL BLOCK}'
        + empty_char_num * '\N{LIGHT SHADE}'
        + f' {ratio:.2%}'
    )


if __name__ == '__main__':
    main()
